### ISSUE TITLE
Padronizar exibição do nome dos relatores

### ISSUE THREAD

**Issue by gileadekelvin** [parlametria/leggo-frontend#496]
**Descrição do bug**
Quando listamos um relator deputado, escrevemos "dep. fulano" quando é senador, escrevemos só o nome, sem o "sen." O partido também não aparece em alguns casos

**Para gerá-lo**
Passo a passo para reproduzir o bug:
1. Vá par ao link https://dev.leggo.org.br/#/proposicao/750/congresso-remoto ou procure pela PL 2630/2020 em https://dev.leggo.org.br/#/congresso-remoto
2. Observe o nome do relator: Angelo Coronel

**Comportamento esperado**
O autor deveria ser Sen. Angelo Coronel (PSD-BA)

**Comment by nazareno** [comment]
Isso não foi já resolvido depois da estruturação de dados, @hadrizia ?
